### ISSUE TITLE
BUG: crash after switch from execa to child_process.spawnSync

### ISSUE THREAD

**Issue by stefreak** [kubernetes-client/javascript#1013]
**Describe the bug**
Observed crash in 0.18.1 that cannot be reproduced in 0.18.0. The key difference is #946 

This was observed in the garden-io/garden CI for windows, and in some cases also macOS

This is the full error and stack trace from our CI:

```
TypeError: The "options" argument must be of type object. Received null
at normalizeSpawnArguments (node:child_process:513:5)
at Object.spawnSync (node:child_process:762:8)
at ExecAuth.spawnSync [as execFn] (pkg/prelude/bootstrap.js:2087:31)
at ExecAuth.getCredential (C:\snapshot\project\tmp\pkg\cli\node_modules\@kubernetes\client-node\dist\exec_auth.js:81:29)
at ExecAuth.applyAuthentication (C:\snapshot\project\tmp\pkg\cli\node_modules\@kubernetes\client-node\dist\exec_auth.js:23:33)
at KubeConfig.applyAuthorizationHeader (C:\snapshot\project\tmp\pkg\cli\node_modules\@kubernetes\client-node\dist\config.js:368:33)
at KubeConfig.applyOptions (C:\snapshot\project\tmp\pkg\cli\node_modules\@kubernetes\client-node\dist\config.js:376:20)
at KubeConfig.applyToRequest (C:\snapshot\project\tmp\pkg\cli\node_modules\@kubernetes\client-node\dist\config.js:99:20)
at KubeApi.request (C:\snapshot\project\tmp\pkg\cli\node_modules\@garden-io\core\src\plugins\kubernetes\api.ts:339:23)
at prepareNamespaces (C:\snapshot\project\tmp\pkg\cli\node_modules\@garden-io\core\src\plugins\kubernetes\namespace.ts:238:15)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at Object.getEnvironmentStatus (C:\snapshot\project\tmp\pkg\cli\node_modules\@garden-io\core\src\plugins\kubernetes\init.ts:85:22)
at C:\snapshot\project\tmp\pkg\cli\node_modules\@garden-io\core\src\actions.ts:1293:24
at wrapped.ensurePrepared (C:\snapshot\project\tmp\pkg\cli\node_modules\@garden-io\core\src\tasks\resolve-provider.ts:338:18)
at wrapped.process (C:\snapshot\project\tmp\pkg\cli\node_modules\@garden-io\core\src\tasks\resolve-provider.ts:241:20)
at TaskNode.process (C:\snapshot\project\tmp\pkg\cli\node_modules\@garden-io\core\src\task-graph.ts:801:20)
at wrapped.processNode (C:\snapshot\project\tmp\pkg\cli\node_modules\@garden-io\core\src\task-graph.ts:436:18)
```

** Client Version **
e.g. `0.18.1`

** Server Version **
irrelevant, it happens before the first connection. The library never connects to the server.

**To Reproduce**

The steps to reproduce are not known as of now. 

Needs further investigation to determine if this is a general issue on windows (or macos).

Windows CI Logs from garden-io/garden CircleCI with the failure using 0.18.1:
https://app.circleci.com/pipelines/github/garden-io/garden/16002/workflows/d66583b9-5d5d-4eea-97bf-26605ed67b8e/jobs/268195

Another build with latest master, where it fails on both macOS and windows, but works on Linux:
https://app.circleci.com/pipelines/github/garden-io/garden/16004/workflows/456e95b5-09bc-4c65-b88d-51eee88bc076

Successful CI with 0.18.0:
https://app.circleci.com/pipelines/github/garden-io/garden/16003/workflows/9443a905-ca51-4aea-bf54-133b2951ac0f/jobs/268238

**Environment (please complete the following information):**
 - OS: Windows, MacOS
 - NodeJS Version 18.12.0
 - Cloud runtime GKE

**Additional context**
This is a very interesting one, because `child_process.spawnSync` actually complains about the third positional argument being null (`options`) – but looking at the code in `exec_auth.ts` it can't possibly be null:

```
        let opts = {};
        if (exec.env) {
            const env = {
                ...process.env,
            };
            exec.env.forEach((elt) => (env[elt.name] = elt.value));
            opts = { ...opts, env };
        }
        const result = this.execFn(exec.command, exec.args, opts); // execFn is an alias of `child_process.spawnSync`
```

**Comment by brendandburns** [comment]
What does your `exec` section in the kubeconfig file look like?

**Comment by stefreak** [comment]
Oh, now that I look at this again I think this also might be related to the fact that we are packaging Garden using [Vercel PKG](https://github.com/vercel/pkg). Vercel PKG [seems to monkeypatch `child_process.spawn`](https://github.com/vercel/pkg/blob/main/prelude/bootstrap.js#L1988) and maybe that is causing our crash
