### ISSUE TITLE
attach fix for UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by scher200** [kubernetes-client/javascript#106]
For anyone with the the following error:
```
ode:16396) UnhandledPromiseRejectionWarning: Error: Server responded with a non-101 status: 500 Internal Server Error
Response Headers Follow:
date: Mon, 24 Sep 2018 16:01:57 GMT
content-length: 75
content-type: text/plain; charset=utf-8

    at WebSocketClient.failHandshake (../nodes/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at ClientRequest.<anonymous> (../nodes/node_modules/websocket/lib/WebSocketClient.js:278:18)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:441:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onread (net.js:639:20)
(node:16396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

just simply override the following code in file node_modules/@kubernetes/client-node/dist/attach.js,
```
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
const querystring = require("querystring");
const web_socket_handler_1 = require("./web-socket-handler");
class Attach {
    constructor(config) {
        this.handler = new web_socket_handler_1.WebSocketHandler(config);
    }
    attach(namespace, podName, containerName, stdout, stderr, stdin, tty) {
        return __awaiter(this, void 0, void 0, function* () {
            const query = {
                stdout: stdout != null,
                stderr: stderr != null,
                stdin: stdin != null,
                tty,
                container: containerName,
            };
            const queryStr = querystring.stringify(query);
            const path = `/api/v1/namespaces/${namespace}/pods/${podName}/attach?${queryStr}`;
            const conn = yield this.handler.connect(path, null, (streamNum, buff) => {
                web_socket_handler_1.WebSocketHandler.handleStandardStreams(streamNum, buff, stdout, stderr);
            });
            if (stdin != null) {
                web_socket_handler_1.WebSocketHandler.handleStandardInput(conn, stdin);
            }
            return conn;
        });
    }
}
exports.Attach = Attach;
//# sourceMappingURL=attach.js.map
```

Hope it works for you too!

**Comment by brendandburns** [comment]
I'll put a better fix for this in the original typescript.

Thanks!

**Comment by scher200** [comment]
no worries

**Comment by edvald** [comment]
Adding this to the linter would be good to detect these types of issues: https://palantir.github.io/tslint/rules/no-floating-promises/

**Comment by PriyankaTwinkel003** [comment]
hi Team,

my node.js application works fine in local.From my local it gets the GCP context and displays the pod lists. However when i run the same application in K8s cluster on GCP it gives below error. I have updated the attach.js file still facing the below issue:-
UnhandledPromiseRejectionWarning:listening at port 4000..
(node:1) UnhandledPromiseRejectionWarning: #<Object>
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
 This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated.
In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
