### ISSUE TITLE
Error following example

### ISSUE THREAD

**Issue by wjsgus95** [kubernetes-client/javascript#1159]
**Describe the bug**
I have my k8s cluster on google kubernetes engine (GKE)

error running
```js
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

console.log(kc)

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

k8sApi.listNamespacedPod('default')
    .then((res) => {
	console.log(res.body);
    });

```

error log
```
/Users/wjsgus95/git-repository/gamebridge/apps/server/node_modules/@kubernetes/client-node/dist/exec_auth.js:87
        throw new Error(result.stderr.toString('utf8'));
                                      ^

TypeError: Cannot read properties of null (reading 'toString')
    at ExecAuth.getCredential (/Users/wjsgus95/git-repository/gamebridge/apps/server/node_modules/@kubernetes/client-node/dist/exec_auth.js:87:39)
    at ExecAuth.applyAuthentication (/Users/wjsgus95/git-repository/gamebridge/apps/server/node_modules/@kubernetes/client-node/dist/exec_auth.js:23:33)
    at KubeConfig.applyAuthorizationHeader (/Users/wjsgus95/git-repository/gamebridge/apps/server/node_modules/@kubernetes/client-node/dist/config.js:368:33)
    at KubeConfig.applyOptions (/Users/wjsgus95/git-repository/gamebridge/apps/server/node_modules/@kubernetes/client-node/dist/config.js:376:20)
    at KubeConfig.applyToRequest (/Users/wjsgus95/git-repository/gamebridge/apps/server/node_modules/@kubernetes/client-node/dist/config.js:99:20)
    at /Users/wjsgus95/git-repository/gamebridge/apps/server/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:9993:95
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

** Client Version **
`0.18.1`

** Server Version **
e.g. `v1.26.5-gke.1200`

**To Reproduce**

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: MacOS
 - NodeJS Version 18
  - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

**Comment by wjsgus95** [comment]
the issue was resolved after running
```
gcloud components install gke-gcloud-auth-plugin
```
and starting new terminal
