### ISSUE TITLE
tslib missing - With version 0.7.0

### ISSUE THREAD

**Issue by FredrikFolkesson** [kubernetes-client/javascript#135]
Hi,

We have javascript project that uses this lib and with 0.7.0 we get an error during runtime like this:

```
module.js:550
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/@kubernetes/client-node/dist/index.js:3:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

We install it with --production flag if that matters. (But the package is listed as a normal dependency and not a dev dependency)

We did not see this problem with version 0.6.0

EDIT:
Checking in the generated index.js file there is now a require to `tslib` that did not exist in `v0.6.0`

**Comment by brendandburns** [comment]
I just pushed `0.7.1` which should fix this...

**Comment by FredrikFolkesson** [comment]
Thanks! :)
