### ISSUE TITLE
ZlibError: zlib: unexpected end of file for cp.cpFromPod method

### ISSUE THREAD

**Issue by bodycombathuang** [kubernetes-client/javascript#1521]
when I use cp.cpFromPod for a file with size about 6MB, I get error
c:\typescript\node_modules\minizlib\index.js:154
      this[_onError](new ZlibError(err))
                     ^
ZlibError: zlib: unexpected end of file
    at Unzip.write (c:\typescript\node_modules\minizlib\index.js:154:22)
    at Unzip.flush (c:\typescript\node_modules\minizlib\index.js:105:10)
    at Unzip.end (c:\typescript\node_modules\minizlib\index.js:111:10)
    at Unpack.end (c:\typescript\node_modules\tar\lib\parse.js:544:21)
    at Pipe.end (c:\typescript\node_modules\fs-minipass\node_modules\minipass\index.js:75:17)
    at ReadStream.[emitEnd2] (c:\typescript\node_modules\fs-minipass\node_modules\minipass\index.js:522:9)
    at ReadStream.[emitEnd] (c:\typescript\node_modules\fs-minipass\node_modules\minipass\index.js:507:21)
    at ReadStream.emit (c:\typescript\node_modules\fs-minipass\node_modules\minipass\index.js:458:27)
    at ReadStream.emit (c:\typescript\node_modules\fs-minipass\index.js:175:22)
    at ReadStream.[maybeEmitEnd] (c:\typescript\node_modules\fs-minipass\node_modules\minipass\index.js:440:12) {
  code: 'Z_BUF_ERROR',
  errno: -5,
  recoverable: false,
  file: 'C:\\Users\\zhhuan\\AppData\\Local\\Temp/8a34ec6b-69f2-41f5-8026-af4c23168279',
  cwd: 'c:/typescript/json',
  tarCode: 'TAR_ABORT'
}

I used latest version

**Comment by brendandburns** [comment]
I suspect that the network connection is getting interrupted, can you try to reproduce this locally with a minikube cluster where network isn't a problem?

**Comment by brendandburns** [comment]
There's also this PR that may help:

https://github.com/kubernetes-client/javascript/pull/1396

**Comment by bodycombathuang** [comment]
hi @brendandburns   1396 does not provide any workaround or solution
if the file size is small, (several bytes), I cannot reproduce, it is reproduced for file that is larger than 5MB each time

**Comment by bodycombathuang** [comment]
https://github.com/kubernetes-client/javascript/blob/master/src/cp.ts
`      async ({ status }) => {
                writerStream.close();
                if (status === 'Failure' || errStream.size()) {
                    throw new Error(`Error from cpFromPod - details: \n ${errStream.getContentsAsString()}`);
                }
                await tar.x({
                    file: tmpFileName,
                    cwd: tgtPath,
                });
            },`

i guess it is because tar.x command is executed before "tar zcf" command is finished
