### ISSUE TITLE
Watch API for Job fails with `Error: unexpected object`

### ISSUE THREAD

**Issue by juliahw** [kubernetes-client/javascript#157]
I'm encountering this error when I use the Watch API to watch a job:

```
/my_dir/node_modules/@kubernetes/client-node/dist/watch.js:51
                throw new Error(`unexpected object: ${JSON.stringify(obj)}`);
                      ^
Error: unexpected object: {"kind":"Job","apiVersion":"batch/v1","metadata":{"name":"example","namespace":"default","selfLink":"/apis/batch/v1/namespaces/default/jobs/example","uid":"15f1d138-f446-11e8-bcf7-0ac7951c158c","resourceVersion":"1562565","creationTimestamp":"2018-11-30T02:17:28Z","labels":{"controller-uid":"15f1d138-f446-11e8-bcf7-0ac7951c158c","job-name":"example"}},"spec":{"parallelism":1,"completions":1,"backoffLimit":6,"selector":{"matchLabels":{"controller-uid":"15f1d138-f446-11e8-bcf7-0ac7951c158c"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"controller-uid":"15f1d138-f446-11e8-bcf7-0ac7951c158c","job-name":"example"}},"spec":{"containers":[{"name":"example","image":"busybox","command":["sleep","30"],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Never","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"conditions":[{"type":"Complete","status":"True","lastProbeTime":"2018-11-30T02:18:00Z","lastTransitionTime":"2018-11-30T02:18:00Z"}],"startTime":"2018-11-30T02:17:28Z","completionTime":"2018-11-30T02:18:00Z","succeeded":1}}
    at LineStream.stream.on (my_dir/node_modules/@kubernetes/client-node/dist/watch.js:51:23)
    at emitOne (events.js:116:13)
    at LineStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at LineStream.Readable.push (_stream_readable.js:208:10)
    at LineStream.Transform.push (_stream_transform.js:147:32)
    at LineStream._pushBuffer (my_dir/node_modules/byline/lib/byline.js:126:17)
    at LineStream._transform (my_dir/node_modules/byline/lib/byline.js:117:8)
    at LineStream.Transform._read (_stream_transform.js:186:10)
```

My Job spec looks like this:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - name: example
        image: busybox
        command: ["sleep",  "30"]
      restartPolicy: Never
```

And my code looks like this:

```ts
import { KubeConfig, Watch } from '@kubernetes/client-node';

const kc = new KubeConfig();
kc.loadFromDefault();

const watch = new Watch(kc);
watch.watch(
  '/apis/batch/v1/namespaces/default/jobs/example',
  {},
  (type, obj) => {
    console.log(obj);
  },
  (err) => {
    if (err) {
      console.log(err);
    }
  },
);

```

The API appears to be returning a valid Job object, but it is being parsed incorrectly. I am using version 0.7.1 of this library.

**Comment by brendandburns** [comment]
But watch shouldn't return `Job` objects, it should return a Watch object (which might contain a Job object)

There's something funky going on here, I will try to reproduce.

**Comment by juliahw** [comment]
> But watch shouldn't return `Job` objects, it should return a Watch object.

Good point! 

Let me know if I can provide any other details.

**Comment by juliahw** [comment]
@brendanburns I've figured out the issue. In my original example, I wrote 

```
/apis/batch/v1/namespaces/default/jobs/example
```

but the correct path was 

```
/apis/batch/v1/watch/namespaces/default/jobs/example
```

It would be great if `watch` could accept only valid endpoints, but the original mistake is on me. Thanks for your help!
