### ISSUE TITLE
LoadFromFile Auth Error via kubeconfig

### ISSUE THREAD

**Issue by zyonnetworks** [kubernetes-client/javascript#1858]
**Describe the bug**
`TypeError: Cannot read properties of null (reading 'toString')
    at ExecAuth.getCredential (/code/test/node_modules/.pnpm/@kubernetes+client-node@1.0.0-rc6/node_modules/@kubernetes/client-node/dist/exec_auth.js:86:39)
    at ExecAuth.applyAuthentication (/code/test/node_modules/.pnpm/@kubernetes+client-node@1.0.0-rc6/node_modules/@kubernetes/client-node/dist/exec_auth.js:23:33)
    at KubeConfig.applyAuthorizationHeader (/code/test/node_modules/.pnpm/@kubernetes+client-node@1.0.0-rc6/node_modules/@kubernetes/client-node/dist/config.js:447:33)
    at KubeConfig.applyOptions (/code/test/node_modules/.pnpm/@kubernetes+client-node@1.0.0-rc6/node_modules/@kubernetes/client-node/dist/config.js:455:20)
    at KubeConfig.applyToHTTPSOptions (/code/test/node_modules/.pnpm/@kubernetes+client-node@1.0.0-rc6/node_modules/@kubernetes/client-node/dist/config.js:109:20)
    at KubeConfig.applyToFetchOptions (/code/test/node_modules/.pnpm/@kubernetes+client-node@1.0.0-rc6/node_modules/@kubernetes/client-node/dist/config.js:85:20)`

** Version **
e.g. `0.21.0`

**To Reproduce**
Load from kc.loadFromFile using kubeconfig file

**Expected behavior**
I expect a reason why the authorization is failing.

** Example Code**
My kubeconfig has this set...
`- name: arn:aws:eks:us-east-1:{ID}:cluster/{Cluster-Name}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - {Cluster-Name}
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false`

**Comment by brendandburns** [comment]
What version of the library are you using? Can you provide your complete kubeconfig file properly formatted (perhaps as an atttachement?

**Comment by zyonnetworks** [comment]
Hi @brendandburns I'm running "@kubernetes/client-node": "^0.21.0"
[configx.txt](https://github.com/user-attachments/files/16843497/configx.txt)
, I've attached kubeconfig...

**Comment by brendandburns** [comment]
Ok, so I think this is being triggered by this code here:

https://github.com/kubernetes-client/javascript/blob/0.21.0/src/exec_auth.ts#L108
or
https://github.com/kubernetes-client/javascript/blob/0.21.0/src/exec_auth.ts#L112

In either case, it means that your `exec` command line call isn't working correctly.

We need some more defensive code there to test if `stdout` or `stderr` is null before trying to print it.

can you try running the specifiec `aws ...` command from that config in your environment and seeing what happens?

**Comment by zyonnetworks** [comment]
Here's the output of the error if stdout or stderr is null...
`{
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawnSync aws',
    path: 'aws',
    spawnargs: [
      '--region',
      'us-east-1',
      'eks',
      'get-token',
      '--cluster-name',
      'MGMT-Cluster',
      '--output',
      'json'
    ]
  },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}`

I was able to successfully connect once I fixed the 'aws' command. Thanks!
