### ISSUE TITLE
Upgrade to 0.22.2 fails due to use of new major version of client-node.

### ISSUE THREAD

**Issue by TonyJDavies** [kubernetes-client/javascript#2014]
**Describe the bug**
When upgraded to latest version `0.22.2` of this library getting the following error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/app/node_modules/openid-client/build/index.js from /home/app/node_modules/@kubernetes/client-node/dist/oidc_auth.js not supported.
Instead change the require of index.js in /home/app/node_modules/@kubernetes/client-node/dist/oidc_auth.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/app/node_modules/@kubernetes/client-node/dist/oidc_auth.js:5:35)
    at /home/app/node_modules/@kubernetes/client-node/dist/oidc_auth_delayed.js:44:70
    at async DelayedOpenIDConnectAuth.applyAuthentication (/home/app/node_modules/@kubernetes/client-node/dist/oidc_auth_delayed.js:44:22)
    at async KubeConfig.apply(--- cut ---)
    at async KubeConfig.applyOptions (/home/app/node_modules/@kubernetes/client-node/dist/config.js:388:9)
    at async KubeConfig.applyToRequest (/home/app/node_modules/@kubernetes/client-node/dist/config.js:110:9)
```

This appears to be due to using the new version of `client-node`.
** Client Version **
`0.22.2`

** Server Version **
e.g. `1.19.1`

**To Reproduce**

**Expected behavior**

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux]
 - NodeJS Version [eg. 10]
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

**Comment by brendandburns** [comment]
I'll try to repro this. I would have thought that the unit tests for this code would have failed though.

Do you have a snippet of code that reproduces this?

Also, what version of Node are you using?

**Comment by cjihrig** [comment]
It looks like #1969 bumped the openid-client dependency from 5.7.0 to 6.1.3. Looking at the [v6.0.0 release notes](https://github.com/panva/openid-client/releases/tag/v6.0.0), that dependency switched to being an ESM module. Since the TypeScript code is transpiled to use `require()`, I'm guessing that explains the error.

**Comment by cjihrig** [comment]
> I would have thought that the unit tests for this code would have failed though.

Similar to what I mentioned in #1975 - it might be worth running the tests against the transpiled code.

**Comment by cjihrig** [comment]
I'm curious what the maintainers would think about reverting #1969 on the v0.x release line, and using this as a reason to move the 1.x release line to ESM. I think that would cause the fewest future headaches.

**Comment by mstruebing** [comment]
@brendandburns I think that would be a very valid breaking change. 
what do you think?

**Comment by cjihrig** [comment]
@brendandburns do you have any thoughts on https://github.com/kubernetes-client/javascript/issues/2014#issuecomment-2481873335?

**Comment by brendandburns** [comment]
I'm ok with that.

**Comment by dominykas** [comment]
Is the intent then to make the client ESM-only as of v1? That's a rather disruptive change if v0.x is going to be discontinued, i.e. it forces people to upgrade to Node.js 22 or to switch to ESM if they want to continue using this?

**Comment by mstruebing** [comment]
I think we want to have the v1.x ESM to be future proof.
We could still release v0.x with the changed k8s API, however, I personally would like to stop that as early as possible as maintaining two main branches is a big burden.

You could still use the already released version, most of the time they are even compatible with newer k8s versions but it also depends a lot of which features you are using.

I think we should probably continue releasing 0.x like 2 versions to give people time to adapt to that change after promoting v1.x as the official release.

What do you think @brendandburns ?

**Comment by dominykas** [comment]
Going to play the devil's advocate a little bit (I don't have a major problem with going ESM-only, assuming the require(ESM) support in Node.js v22+ is less experimental than the documentation implies[^1]).

Aside from the API change (which is very nice!), one of the most attractive features of v1 is the switch to `fetch`. Having to ignore the various alerts about old vulnerabilities in `request` is something that is very annoying in the 0.x. The switch to ESM will significantly raise the barrier for switching - people will either have to upgrade to Node.js v22 (which they should, in the next 12-24 months anyways, but we all know how these things go) or they will have to rewrite their code in ESM (which is expensive and is very hard to justify in terms of cost vs benefit).

Is there any chance v1 could be released in dual-mode? I haven't done this, but there's plenty of packages in the ecosystem that release both - CJS and ESM inside? Or is that affected by dependencies?


[^1]: Prediction: removing the command line flag will make people start using it now, and that means the implementation will be effectively locked in - changing it even behind a major version would be very disruptive.

**Comment by christhegrand** [comment]
This change is causing problems for me. It doesn't work out of the box anymore when imported from Next, and I can't get it to work with Jest either.

**Comment by cjihrig** [comment]
@christhegrand are you using the v0.x release line or the v1.x release line? If it is the v0.x branch, I think a patch reverting https://github.com/kubernetes-client/javascript/pull/1969 (or a similar code change) might do the trick for people that can't update yet.

**Comment by christhegrand** [comment]
This is when using 1.0.0.

**Comment by lamuertepeluda** [comment]
Guys this is a useful library! Please, don't join the blasted ESM-only Taliban club (=== those nasty people believing it's ESM or death)!

There is no point of doing this, really! In Node land, this is far for being future proof! This is just a disruptive change that will leave many people with vulnerabilities or bugs that will never be fixed, for what? [Making less than 15% devs happy](https://github.com/wooorm/npm-esm-vs-cjs)?

It is extremely easy to build a TS package for both CJS and ESM nowadays, and leave the developers choose what to do, and you can turn to ESM later on, when the node ecosystem is more mature (I predict no less than 3 years).

Take me, I am tied to Node 20 right now...

```bash
❯ node --experimental-require-module
Welcome to Node.js v20.17.0.
Type ".help" for more information.
> (node:85321) ExperimentalWarning: Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
> var kc = require('@kubernetes/client-node')
Uncaught RangeError: Maximum call stack size exceeded
    at Object.openSync (node:fs:570:18)
    at readFileSync (node:fs:452:35)
    at getSourceSync (node:internal/modules/esm/load:85:14)
    at defaultLoadSync (node:internal/modules/esm/load:201:32)
    at ModuleLoader.getModuleWrapForRequire (node:internal/modules/esm/loader:362:24)
    at new ModuleJobSync (node:internal/modules/esm/module_job:276:32)
    at ModuleLoader.getModuleWrapForRequire (node:internal/modules/esm/loader:403:11)
    at new ModuleJobSync (node:internal/modules/esm/module_job:276:32)
    at ModuleLoader.getModuleWrapForRequire (node:internal/modules/esm/loader:403:11)
```

there aren't any workarounds. Jest/TS-Jest even worse.

### Solution

In many dual libraries I need to build, I use [tsup](https://tsup.egoist.dev/), a blazing fast builder that makes this kind of tasks easy now, in 2025.

This is the `tsup.config.ts` I am using and I believe this can be easily be adapted for this project

```ts
import type { Options } from 'tsup';

const env = process.env.NODE_ENV;

export const tsup: Options = {
  publicDir: './src/public/',
  splitting: true,
  sourcemap: true, // source map is only available in prod
  clean: true, // rimraf disr
  dts: true, // generate dts file for main module
  format: ['cjs', 'esm'], // generate cjs and esm files
  minify: env === 'production',
  bundle: true,
  skipNodeModulesBundle: true,
  // noExternal: ['packages that need to be bundled'],
  entryPoints: ['src/index.ts'],
  watch: false,
  target: 'esnext',
  outDir: 'dist',
  entry: ['src/index.ts']
};

```

You won't need big changes for tsconfig but I can provide some assist if you need.

**Comment by christhegrand** [comment]
For what it's worth, I did eventually get this library to work with Jest [by using the hack mentioned here](https://github.com/jestjs/jest/issues/15275#issuecomment-2495971960), but it's pretty gross.

**Comment by cjihrig** [comment]
@lamuertepeluda the issue is not about transpiling this library to CJS and ESM. The issue is that we have multiple dependencies that have already moved to being ESM only.

> there aren't any workarounds.

Have you tried dynamic import? If you have found a bug in Node's `--experimental-require-module` functionality, I encourage you to open an issue on the Node core issue tracker, as I believe they are currently in the process of trying to backport unflagged `require(esm)`.

Side note: Would you mind moderating your comment relating to the Taliban. I'd say that is off-topic at best.

**Comment by cjihrig** [comment]
I'm going to close this. At this point, I think this issue has run its course. For the v0.x branch, I think rolling back openid-client might still be on the table though if anyone wants to pursue that.

**Comment by philippkolbe** [comment]
@christhegrand Could you share your solution? I tried the [proposed setup](https://github.com/jestjs/jest/issues/15275#issuecomment-2495971960) from the issue you linked but that did not work for me.

So, I am still stuck on getting jest to work with the kubernetes client-node library.

And looks like several other people from this [stackoverflow post](https://stackoverflow.com/questions/79420894/jest-encountered-unexpected-token-export-in-node-module-kubernetes-client-no) are stuck as well.

**Comment by christhegrand** [comment]
In order to make this library work with Jest, I added this transform logic to the jest.config.js file that ts-jest was using:

```
  transform: {
    "node_modules/@kubernetes/client-node/dist/index.js": [
      "ts-jest",
      {
        tsconfig: "tsconfig.test.json",
        isolatedModules: true
      }
    ],
    "node_modules/openid-client/build/index.js": [
      "ts-jest",
      {
        tsconfig: "tsconfig.test.json",
        isolatedModules: true
      }
    ],
    "node_modules/oauth4webapi": [
      "ts-jest",
      {
        tsconfig: "tsconfig.test.json",
        isolatedModules: true
      }
    ],
    "^.+\\.(t|j)s$": [
      "ts-jest",
      {
        tsconfig: "tsconfig.test.json",
        isolatedModules: true
      }
    ]
  },
  transformIgnorePatterns: [
    "/node_modules/(?!(@kubernetes/client-node|openid-client|oauth4webapi)/)"
  ]
};
```

and I added a new tsconfig file specifically for the tests:

```
{
  "compilerOptions": {
    "allowJs": true
  },
  "extends": "./tsconfig.json"
}
```

Then I updated the tests to look for tests files in the directory where the Typescript files for the tests were located instead of in the directory where the compiled JS files were located.

**Comment by philippkolbe** [comment]
@christhegrand 
Thanks a lot for sending your configuration. It did not work for me out of the box - I assume because we were using different versions of the library. Here is a summary
- the `jose` library also needs to be excluded
- there is no need for a `transform` `ts-jest` configuration per ESM node_module. Excluding the libraries in `transformIgnorePatterns` is enough.
- `tsconfig.json` needs to contain `"esModuleInterop": true`

So this is the `jest.config.js`:
```
module.exports = {
  testEnvironment: 'node',
  preset: 'ts-jest',
  moduleFileExtensions: ['js', 'json', 'ts', 'tsx', 'jsx', 'node'],
  transform: {
    // (Added support for .tsx files but not required)
    '^.+\\.(t|j)sx?$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.test.json',
      },
    ],
    // (No need for module specific ts-jest configurations)...
  },
  transformIgnorePatterns: [
    // Added jose library (probably this ESM dependency was added in the newer versions)
    // This will work for @kuberenets/client-node version 1.1.2
    '/node_modules/(?!(@kubernetes/client-node|openid-client|oauth4webapi|jose)/)',
  ],
};

```

This is the `tsconfig.json`:

```
{
  "compilerOptions": {
    "module": "commonjs" /* Specify what module code is generated. */,

    // THIS IS IMPORTANT!
    "esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */
  },
  "include": [
    "src/**/*" // Include all files in the 'src' folder
  ]
}

```

And this is `tsconfig.test.json` (unchanged):

```
{
  "compilerOptions": {
    "allowJs": true
  },
  "extends": "./tsconfig.json"
}

```


I also set up a stackblitz with a minimal sample which works for `@kuberenets/client-node` version `1.1.2` (run `npm run test`):
https://stackblitz.com/edit/stackblitz-starters-un7zge3j?file=jest.config.js

**Comment by saulrobe** [comment]
> This change is causing problems for me. The library doesn't work out of the box anymore when imported from within a NextJS application, and [I can't get it to work with Jest either](https://github.com/jestjs/jest/issues/15275).

@christhegrand Did you get this issue resolved with your nextjs app or just the jest part? I am having trouble with the client version 1.0.0+ working within my nextjs app.

**Comment by christhegrand** [comment]
I can't remember now how I addressed the issues with importing from Next. We've since modified our code so we don't need to use this library at all and are about to remove the dependency.
