### ISSUE TITLE
Exec error : 'Unexpected server response: 400'

### ISSUE THREAD

**Issue by lakshaygaur** [kubernetes-client/javascript#337]
Im trying to exec on a running container but everytime i run exec with this sdk i get this following error.

`type: 'error',
  message: 'Unexpected server response: 400',
  error: Error: Unexpected server response: 400`

Im using Azure's AKS service and Im loading the conf file from cluster-data provided by azure cli.

**Comment by brendandburns** [comment]
400 == bad request, your request is malformed in some way.

from a detail perspective, the server is attempting to create a web socket to support the `exec` but the initial request is returning a 400 because that request is malformed.

You should be able to catch this error and get more details from the response body as to why the request is malformed.

**Comment by lakshaygaur** [comment]
k8sApi client is working fine, I can list pods and namespaces with the same configuration. But I dont see anything which could point to malformed request details.

Here is my error log trace:

```
ErrorEvent {
  target: 
   WebSocket {
     domain: null,
     _events: { open: [Object], error: [Object], message: [Object] },
     _eventsCount: 3,
     _maxListeners: undefined,
     readyState: 3,
     protocol: '',
     _binaryType: 'nodebuffer',
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _closeCode: 1006,
     _extensions: {},
     _receiver: null,
     _sender: null,
     _socket: null,
     _isServer: false,
     _redirects: 0,
     url: 'wss://zeeve-fabric-dns-5278f591.hcp.centralindia.azmk8s.io:443/api/v1/namespaces/blockchain-buyer/pods/peer-1buyer-hlf-peer-85c8f5bf88-t9fkp/exec?stdout=true&stderr=true&stdin=true&tty=false&command=%2Fbin%2Fsh%20-c%20%22ls%22&container=peer-1buyer-hlf-peer-85c8f5bf88-t9fkp',
     _req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /api/v1/namespaces/blockchain-buyer/pods/peer-1buyer-hlf-peer-85c8f5bf88-t9fkp/exec?stdout=true&stderr=true&stdin=true&tty=false&command=%2Fbin%2Fsh%20-c%20%22ls%22&container=peer-1buyer-hlf-peer-85c8f5bf88-t9fkp HTTP/1.1\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: pz+NaUc4gauDrihDYd8Jhg==\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nAuthorization: Bearer eec6c97417924bd27f0db366cdc93c96\r\nSec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\nSec-WebSocket-Protocol: v4.channel.k8s.io, v3.channel.k8s.io, v2.channel.k8s.io, channel.k8s.io\r\nHost: zeeve-fabric-dns-5278f591.hcp.centralindia.azmk8s.io\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: undefined,
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/api/v1/namespaces/blockchain-buyer/pods/peer-1buyer-hlf-peer-85c8f5bf88-t9fkp/exec?stdout=true&stderr=true&stdin=true&tty=false&command=%2Fbin%2Fsh%20-c%20%22ls%22&container=peer-1buyer-hlf-peer-85c8f5bf88-t9fkp',
        _ended: true,
        res: [Object],
        aborted: 1568096835863,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] } },
  type: 'error',
  message: 'Unexpected server response: 404',
  error: Error: Unexpected server response: 404
    at ClientRequest.req.on (/home/lakshay/Desktop/node_test/azure-js/node_modules/ws/lib/websocket.js:596:7)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11) }
```

**Comment by brendandburns** [comment]
In this particular case you're getting a `404` message, presumably because `/api/v1/namespaces/blockchain-buyer/pods/peer-1buyer-hlf-peer-85c8f5bf88-t9fkp` doesn't exist.

I'm closing this issue since I think you have sufficient info to debug. If you find a problem with the client library, please re-open this issue.

Thanks!
