### ISSUE TITLE
Error while getting list of namespaces

### ISSUE THREAD

**Issue by ameerthehacker** [kubernetes-client/javascript#339]
/Users/alexmiles/.nvm/versions/node/v8.11.1/lib/node_modules/kubelive/node_modules/@kubernetes/client-node/dist/config_types.js:18
            throw new Error(`clusters[${i}].cluster.server is missing`);
            ^

Error: clusters[1].cluster.server is missing
    at /Users/alexmiles/.nvm/versions/node/v8.11.1/lib/node_modules/kubelive/node_modules/@kubernetes/client-node/dist/config_types.js:18:19
    at Function._.map._.collect (/Users/alexmiles/.nvm/versions/node/v8.11.1/lib/node_modules/kubelive/node_modules/underscore/underscore.js:205:24)
    at Object.newClusters (/Users/alexmiles/.nvm/versions/node/v8.11.1/lib/node_modules/kubelive/node_modules/@kubernetes/client-node/dist/config_types.js:6:14)
    at KubeConfig.loadFromString (/Users/alexmiles/.nvm/versions/node/v8.11.1/lib/node_modules/kubelive/node_modules/@kubernetes/client-node/dist/config.js:94:40)
    at KubeConfig.loadFromFile (/Users/alexmiles/.nvm/versions/node/v8.11.1/lib/node_modules/kubelive/node_modules/@kubernetes/client-node/dist/config.js:65:14)
    at KubeConfig.loadFromDefault (/Users/alexmiles/.nvm/versions/node/v8.11.1/lib/node_modules/kubelive/node_modules/@kubernetes/client-node/dist/config.js:201:22)
    at Object.<anonymous> (/Users/alexmiles/.nvm/versions/node/v8.11.1/lib/node_modules/kubelive/kube/api.js:5:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by brendandburns** [comment]
Your kubeconfig isn't parsing correctly. Can you attach the kubeconfig (secrets redacted)

Thanks

**Comment by brendandburns** [comment]
Closing due to lack of response. Please feel free to re-open with the requested information.
