### ISSUE TITLE
exec error: 'Unexpected server response: 401'

### ISSUE THREAD

**Issue by gkze** [kubernetes-client/javascript#353]
While running the [exec example code](https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/exec/exec-example.ts) (JavaScript-ified version pasted below for accuracy), I receive the following error:

```javascript
  error: Error: Unexpected server response: 401
      at ClientRequest.<anonymous> (/Users/gkontridze/Development/github.plaid.com/plaid/constellation/node_modules/ws/lib/websocket.js:595:7)
      at ClientRequest.emit (events.js:210:5)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
      at TLSSocket.socketOnData (_http_client.js:456:22)
      at TLSSocket.emit (events.js:210:5)
      at addChunk (_stream_readable.js:308:12)
      at readableAddChunk (_stream_readable.js:289:11)
      at TLSSocket.Readable.push (_stream_readable.js:223:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23)
```

Running the following JavaScript code (`node exec.js whoami`):

```javascript
const k8s = require('@kubernetes/client-node');

const command = process.argv[2];
console.log(command);

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const exec = new k8s.Exec(kc);
exec.exec('default', 'nginx', 'nginx', command,
    process.stdout, process.stderr, process.stdin,
    false /* tty */,
    (status) => {
        // tslint:disable-next-line:no-console
        console.log('Exited with status:');
        // tslint:disable-next-line:no-console
        console.log(JSON.stringify(status, null, 2));
    }
).catch(err => console.log(err));
```

Here is the byte-for-byte request string, set on the `_header` property of the `ClientRequest` sub-object of the `WebSocket` object:

```javascript
'GET /api/v1/namespaces/default/pods/hellokube/exec?stdout=true&stderr=true&stdin=true&tty=false&command=&container=hellokube HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: [redacted]\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Sec-WebSocket-Protocol: v4.channel.k8s.io, v3.channel.k8s.io, v2.channel.k8s.io, channel.k8s.io\r\n' +
        'Host: localhost:6443\r\n' +
        '\r\n
```

Here is my Docker Compose configuration:

```yaml
---
version: "3.7"

services:
  kubernetes:
    image: rancher/k3s:latest
    ports:
    - 6443:6443
    privileged: true
    command:
    - server
    environment:
      K3S_KUBECONFIG_OUTPUT: /etc/k3s_out/kubeconfig.yaml
    volumes:
    - ./tmp/k3s_out:/etc/k3s_out
```

Here is the command I used to run an `nginx` Pod:

```bash
kubectl run nginx --attach=true --generator=run-pod/v1 --image=nginx --command -- sh -c 'nginx -g "daemon off;"'
```

CC @brendanburns I actually tried to reproduce this with `kind` but was unable to, unfortunately I think this seems to be isolated to [Rancher's k3s](https://github.com/rancher/k3s) implementation. However, when I exec against a Pod with `kubectl` pointed at k3s, it runs fine.

I was able to get exec to work with [websocat](https://github.com/vi/websocat):

```bash
websocat -Ek 'wss://admin:[redacted]@localhost:6443/api/v1/namespaces/default/pods/nginx/exec?stdout=true&stderr=true&stdin=true&tty=false&command=whoami&container=nginx'
```

**Comment by brendandburns** [comment]
I think that the cause of this is the empty-header array (or lack of such handling) in exec_auth.ts I will try to repro in unit test...

**Comment by brendandburns** [comment]
Yep, that was the bug. Sent a fix in #354

**Comment by gkze** [comment]
Thank you so much for the fix!!

**Comment by brendandburns** [comment]
This was pushed in release `0.11.0` please test and see if it fixes your issue.
