### ISSUE TITLE
PortForward crashes

### ISSUE THREAD

**Issue by runi95** [kubernetes-client/javascript#459]
I'm using port forward to forward HTTP requests to a REST service sitting in a test cluster. The below code snippet is how I'm connecting to the pod

```
const forward = new k8s.PortForward(kc);
const server = net.createServer((socket) => {
  forward.portForward('my-namespace', 'my-pod', [8080], socket, socket, socket, 3);
});
```

This websocket connection breaks after a while and gives me the following error

```
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:453:14)
    at /home/runar/flow-command-line-interface/node_modules/@kubernetes/client-node/dist/portforward.js:48:32
    at WebSocket.client.onmessage (/home/runar/flow-command-line-interface/node_modules/@kubernetes/client-node/dist/web-socket-handler.js:145:47)
    at WebSocket.onMessage (/home/runar/flow-command-line-interface/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/runar/flow-command-line-interface/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/runar/flow-command-line-interface/node_modules/ws/lib/receiver.js:413:14)
    at Receiver.getData (/home/runar/flow-command-line-interface/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/home/runar/flow-command-line-interface/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/home/runar/flow-command-line-interface/node_modules/ws/lib/receiver.js:74:10)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Receiver.Writable.write (_stream_writable.js:303:10)
    at TLSSocket.socketOnData (/home/runar/flow-command-line-interface/node_modules/ws/lib/websocket.js:864:35)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
```

The above error refers to this line in source code https://github.com/kubernetes-client/javascript/blob/master/src/portforward.ts#L63

However if I use `kubectl port-forward` instead of the Node client library I'm able to keep a connection going without this issue

**Comment by brendandburns** [comment]
This library uses web sockets instead of SPDY, I suspect that there are differences in how something in the network is handling the web sockets connection. Are there any network proxies in the middle?

Also are you running websockets over the port-forward (e.g. nested web-sockets) I could imagine that could cause problems.

**Comment by runi95** [comment]
There are no network proxies in the middle.
