### ISSUE TITLE
Can't use tailLines parameter of readNamespacedPodLog

### ISSUE THREAD

**Issue by rafagsiqueira** [kubernetes-client/javascript#490]
Version "@kubernetes/client-node": "0.12.0"

This code:
```
const api = this.kc.makeApiClient(CoreV1Api) as CoreV1Api;
const {body} = await api.readNamespacedPodLog(name, namespace, null, null, null, null, null, null, null, 20);
```
generates the following error:
```
{
  "errors": [
    {
      "message": "HTTP request failed",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "podLog"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "response": {
            "statusCode": 400,
            "body": {
              "kind": "Status",
              "apiVersion": "v1",
              "metadata": {},
              "status": "Failure",
              "message": "strconv.ParseInt: parsing \"\": invalid syntax",
              "reason": "BadRequest",
              "code": 400
            },
            "headers": {
              "audit-id": "58c6ef54-66f0-4a91-bcb1-1ae6d08d52e3",
              "cache-control": "no-cache, private",
              "content-type": "application/json",
              "date": "Mon, 24 Aug 2020 19:34:12 GMT",
              "content-length": "161",
              "connection": "close"
            },
            "request": {
              "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "hostname:443",
                "port": "443",
                "hostname": "hostname",
                "hash": null,
                "search": "?container=&follow=&insecureSkipTLSVerifyBackend=&limitBytes=&pretty=&previous=&sinceSeconds=&tailLines=20",
                "query": "container=&follow=&insecureSkipTLSVerifyBackend=&limitBytes=&pretty=&previous=&sinceSeconds=&tailLines=20",
                "pathname": "/api/v1/namespaces/application/pods/tips-dev-68668c76f9-d7xbc/log",
                "path": "/api/v1/namespaces/application/pods/tips-dev-68668c76f9-d7xbc/log?container=&follow=&insecureSkipTLSVerifyBackend=&limitBytes=&pretty=&previous=&sinceSeconds=&tailLines=20",
                "href": "https://hostname:443/api/v1/namespaces/application/pods/tips-dev-68668c76f9-d7xbc/log?container=&follow=&insecureSkipTLSVerifyBackend=&limitBytes=&pretty=&previous=&sinceSeconds=&tailLines=20"
              },
              "method": "GET",
              "headers": {
                "Accept": "application/json",
                "Authorization": "Bearer <token>"
              }
            }
          },
          "body": {
            "kind": "Status",
            "apiVersion": "v1",
            "metadata": {},
            "status": "Failure",
            "message": "strconv.ParseInt: parsing \"\": invalid syntax",
            "reason": "BadRequest",
            "code": 400
          },
          "statusCode": 400,
          "name": "HttpError",
          "stacktrace": [
            "HttpError: HTTP request failed",
            "    at Request._callback (/Users/rafasiqueira/Work/tips-api/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:14944:40)",
            "    at Request.self.callback (/Users/rafasiqueira/Work/tips-api/node_modules/request/request.js:185:22)",
            "    at Request.emit (events.js:314:20)",
            "    at Request.<anonymous> (/Users/rafasiqueira/Work/tips-api/node_modules/request/request.js:1154:10)",
            "    at Request.emit (events.js:314:20)",
            "    at IncomingMessage.<anonymous> (/Users/rafasiqueira/Work/tips-api/node_modules/request/request.js:1076:12)",
            "    at Object.onceWrapper (events.js:420:28)",
            "    at IncomingMessage.emit (events.js:326:22)",
            "    at endReadableNT (_stream_readable.js:1226:12)",
            "    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
          ]
        }
      }
    }
  ],
  "data": null
}
```
This code works without a problem:
```
const api = this.kc.makeApiClient(CoreV1Api) as CoreV1Api;
const {body} = await api.readNamespacedPodLog(name, namespace);
```
The issue seems related to the tailLines parameter.

**Comment by brendandburns** [comment]
I'll try to reproduce, the go server is trying to parse an empty string as an int and failing. My guess is that one of the other parameters is required as well if tailLines is not null.

**Comment by brendandburns** [comment]
So it looks like you need to send more than just tailLines, the following works for me:

```javascript
k8sApi.readNamespacedPodLog("coredns-8bbb65c89-5bgbj", "kube-system", null, null, null, 10000, null, false, 20, 20)
```

The URL we are sending is:
`.../log?container=&follow=&insecureSkipTLSVerifyBackend=&limitBytes=10000&pretty=&previous=false&sinceSeconds=0&tailLines=20'`

(note all of those empty-string parameters)

It seems like the go server tries to parse empty strings. This seems like brittle behavior on the part of kubernetes api-server.

**Comment by rafagsiqueira** [comment]
Thank you @brendandburns, I will try that way.

**Comment by brendandburns** [comment]
@rafagsiqueira 
Quick update on this if you pass `undefined` instead of `null` it should work.

(this is not awesome, the code should treat `undefined` and `null` the same imho.

**Comment by rafagsiqueira** [comment]
@brendanburns, it does work. Thank you! Albeit not very legible. Had to make this call to add timestamps to the logs:
`api.readNamespacedPodLog(name, namespace, undefined, false, false, undefined, undefined, false, undefined, undefined, true);`
Ideal approach would be to use interfaces and named parameters for the calls, perhaps?
