### ISSUE TITLE
Change stream-buffers to a dependency (currently a devDependency)

### ISSUE THREAD

**Issue by edify42** [kubernetes-client/javascript#503]
Hey Maintainers!

I stumbled across a weird issue when we pushed our package to npm that uses this library:

```bash
internal/modules/cjs/loader.js:638
    throw err;
    ^
 
Error: Cannot find module 'stream-buffers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/lib/buildkite-agent/.npm-global/lib/node_modules/@lendi/lcd/node_modules/@kubernetes/client-node/dist/cp.js:5:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

The package itself is a CLI tool that gets installed globally (`yarn global add @lendi/lcd`) - it's private though

We had no problems during our testing phase as we used `ts-node` within our source code location and `stream-buffer` was available as a devDependency.

From this file, it looks like it should be a dependency as it's imported as such: https://github.com/kubernetes-client/javascript/blob/master/src/cp.ts

Node version: v10.22.4

**Comment by Chengxuan** [comment]
We are also hitting this in our pipeline.

**Comment by brendandburns** [comment]
Yeah, looks like that should be a dependency. Please feel free to send a PR to fix this.

Thanks!

**Comment by brendandburns** [comment]
Closing since #506 merged.

**Comment by brendandburns** [comment]
I will cut a new release soon with the right dependencies.

**Comment by popomore** [comment]
@brandonc Can you release new version for bugfix?

**Comment by maikknebel** [comment]
Release 0.12.1 says this has been solved, but if i install the latest version via npm (which is 0.12.1) the changes from pull request #506 are missing.
