### ISSUE TITLE
attach return 500 (internal server error)

### ISSUE THREAD

**Issue by stavalfi** [kubernetes-client/javascript#540]
maybe it's related to https://github.com/kubernetes-client/javascript/issues/106 but that issue is 2 years old.

---

```
const kc = new k8s.KubeConfig()
kc.loadFromDefault()
const attach = new k8s.Attach(kc)
await attach.attach(
      'default',
      'job-fd8209368b41ab5527b4800750f6fcf85fb38d81-g4v9v',
      'building-project',
      process.stdout,
      process.stderr,
      null /* stdin */,
      false /* tty */,
    )
```

error:

```
ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      error: [Function],
      message: [Function]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    readyState: 3,
    protocol: '',
    _binaryType: 'nodebuffer',
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _closeCode: 1006,
    _extensions: {},
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    url: 'wss://127.0.0.1:32768/api/v1/namespaces/default/pods/job-fd8209368b41ab5527b4800750f6fcf85fb38d81-g4v9v/attach?stdout=true&stderr=true&stdin=false&tty=false&container=building-project',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /api/v1/namespaces/default/pods/job-fd8209368b41ab5527b4800750f6fcf85fb38d81-g4v9v/attach?stdout=true&stderr=true&stdin=false&tty=false&container=building-project HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: NiztjvxUnmM9h4F1pubraw==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Sec-WebSocket-Protocol: v4.channel.k8s.io, v3.channel.k8s.io, v2.channel.k8s.io, channel.k8s.io\r\n' +
        'Host: 127.0.0.1:32768\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/v1/namespaces/default/pods/job-fd8209368b41ab5527b4800750f6fcf85fb38d81-g4v9v/attach?stdout=true&stderr=true&stdin=false&tty=false&container=building-project',
      _ended: false,
      res: [IncomingMessage],
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'Unexpected server response: 500',
  error: Error: Unexpected server response: 500
      at ClientRequest.<anonymous> (/Users/stavalfi/projects/nc/node_modules/ws/lib/websocket.js:576:7)
      at ClientRequest.emit (events.js:311:20)
      at ClientRequest.EventEmitter.emit (domain.js:482:12)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
      at TLSSocket.socketOnData (_http_client.js:476:22)
      at TLSSocket.emit (events.js:311:20)
      at TLSSocket.EventEmitter.emit (domain.js:482:12)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
}
```

in debug mode, I see at the buttom "internal server error":

![image](https://user-images.githubusercontent.com/12954665/97915627-7315c200-1d5a-11eb-84c1-93d3e9895324.png)

---------------

```
minikube version: v1.12.3
commit: 2243b4b97c131e3244c5f014faedca0d846599f5
---
Docker version 19.03.13, build 4484c46d9d
--
macos: 10.15.1 (19B2093)
--
node v12.16.1 (also tested in v14.15.0 (latest stable node version at this moment) and saw same error)
```

**Comment by stavalfi** [comment]
duplicate in mistake

**Comment by williamd5** [comment]
Someone else could also make the same mistake. It would be great not to edit the issue like this
