### ISSUE TITLE
ConnectPostNamespacedPodExec - fails can't upgrade to websockets

### ISSUE THREAD

**Issue by Daxcor69** [kubernetes-client/javascript#551]
I am trying to execute a command in a pod from the api CoreV1Api and I get an error, here is error object... Note I have edited out any  host info and bearer token, so that is not the issue.  Based on googling it is an issue with unable to upgrade the connection.  Thoughts?

```
response: <ref *1> IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      errored: null,
      closed: false,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      end: [Array],
      close: [Array],
      data: [Function (anonymous)],
      error: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: '128cdcm',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '128cdc15-fb51-47om',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 720,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers: {
      'audit-id': 'ce508a49-608f-4d1f-8384-677d63801925',
      'cache-control': 'no-cache, private',
      'content-type': 'application/json',
      date: 'Mon, 09 Nov 2020 19:17:32 GMT',
      'content-length': '139',
      connection: 'close'
    },
    rawHeaders: [
      'Audit-Id',
      'ce508a49-608f-4d1f-8384-677d63801925',
      'Cache-Control',
      'no-cache, private',
      'Content-Type',
      'application/json',
      'Date',
      'Mon, 09 Nov 2020 19:17:32 GMT',
      'Content-Length',
      '139',
      'Connection',
      'close'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 400,
    statusMessage: 'Bad Request',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: '128cdc15-fbean.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '128cdc15-fb51-471c-bca3-6n.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [ClientRequest],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 720,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7/exec?command=ftpasswd%20--passwd%20--file%20%2Fetc%2Fproftpd%2Fuser%2Fuser.conf%20--delete-user%20--name%20brad&container=prosftpd-pod&stderr=true&stdin=true HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Authorization: Bearer 4dcb37f13c68a3\r\n' +
        'host: 128cdc15-fbalocean.com\r\n' +
        'content-length: 0\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7/exec?command=ftpasswd%20--passwd%20--file%20%2Fetc%2Fproftpd%2Fuser%2Fuser.conf%20--delete-user%20--name%20brad&container=prosftpd-pod&stderr=true&stdin=true',
      _ended: true,
      res: [Circular *1],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '128df9e20a7f53.k8s.sdf.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    request: Request {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      method: 'POST',
      headers: [Object],
      uri: [Url],
      useQuerystring: false,
      ca: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 44 4a 7a 43 43 41 67 2b 67 41 77 49 42 41 67 49 43 42 6e ... 1105 more bytes>,
      callback: [Function (anonymous)],
      readable: true,
      writable: true,
      explicitMethod: true,
      _qs: [Querystring],
      _auth: [Auth],
      _oauth: [OAuth],
      _multipart: [Multipart],
      _redirect: [Redirect],
      _tunnel: [Tunnel],
      setHeader: [Function (anonymous)],
      hasHeader: [Function (anonymous)],
      getHeader: [Function (anonymous)],
      removeHeader: [Function (anonymous)],
      localAddress: undefined,
      pool: [Object],
      dests: [],
      __isRequestRequest: true,
      _callback: [Function (anonymous)],
      proxy: null,
      tunnel: true,
      setHost: true,
      originalCookieHeader: undefined,
      _disableCookies: true,
      _jar: undefined,
      port: 443,
      host: '128c20a7f53.k8s.dfs.com',
      url: [Url],
      path: '/api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7/exec?command=ftpasswd%20--passwd%20--file%20%2Fetc%2Fproftpd%2Fuser%2Fuser.conf%20--delete-user%20--name%20brad&container=prosftpd-pod&stderr=true&stdin=true',
      _json: true,
      httpModule: [Object],
      agentClass: [Function: Agent],
      agent: [Agent],
      _started: true,
      href: 'https://12sdf3.k8s.my.com/api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7/exec?command=ftpasswd%20--passwd%20--file%20%2Fetc%2Fproftpd%2Fuser%2Fuser.conf%20--delete-user%20--name%20brad&container=prosftpd-pod&stderr=true&stdin=true',
      req: [ClientRequest],
      ntick: true,
      response: [Circular *1],
      originalHost: '128cdc15-om',
      originalHostHeaderName: 'host',
      responseContent: [Circular *1],
      _destdata: true,
      _ended: true,
      _callbackCalled: true,
      [Symbol(kCapture)]: false
    },
    toJSON: [Function: responseToJSON],
    caseless: Caseless { dict: [Object] },
    body: {
      kind: 'Status',
      apiVersion: 'v1',
      metadata: {},
      status: 'Failure',
      message: 'Upgrade request required',
      reason: 'BadRequest',
      code: 400
    },
    [Symbol(kCapture)]: false,
    [Symbol(RequestTimeout)]: undefined
  },
  body: {
    kind: 'Status',
    apiVersion: 'v1',
    metadata: {},
    status: 'Failure',
    message: 'Upgrade request required',
    reason: 'BadRequest',
    code: 400
  },
  statusCode: 400
}
```

**Comment by brendandburns** [comment]
You can't use CoreV1API for exec (sorry we should probably strip those methods from swagger before generating) please have a look at the exec example here:

https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/exec/exec-example.ts

**Comment by Daxcor69** [comment]
Ok i followed the ts example you suggested. i converted it to javascript as that is what I am used to.  I am not sure why I am getting the error. There is no information other than 'Unexpected server response: 400.  I am running these two processes on the same computer with the same .kube/config file.  The only difference I can see is the client used to access the api.

```
async function go() {
    try {
        var k8s = require("@kubernetes/client-node");
        var kc = new k8s.KubeConfig();
        kc.loadFromDefault();
        var exec = new k8s.Exec(kc);
        const status = await exec.exec('default', 'prosftpd-pod-584bd54ffc-24gq7', 'proftpd-pod', 'ls', process.stdout, process.stderr, process.stdin, true);
        return status;
    } catch (error) {
        console.error(error);
    }
}
const status = go();
console.log('Exited with status:');
console.log(JSON.stringify(status, null, 2));
```
When I run this i get an error

```
ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      error: [Function],
      message: [Function]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    readyState: 3,
    protocol: '',
    _binaryType: 'nodebuffer',
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _closeCode: 1006,
    _extensions: {},
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    url: 'wss://128cdc15-fb51-471c-bca3-62a9e20a7f53.k8s.ondigitalocean.com/api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7/exec?stdout=true&stderr=true&stdin=true&tty=true&command=ls&container=proftpd-pod',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7/exec?stdout=true&stderr=true&stdin=true&tty=true&command=ls&container=proftpd-pod HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: cRo3F4Yg817z99Utox760g==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Authorization: Bearer 82dbe9f8e418c55b0b333a8edbab50e437026781d1f860a84c7c4f682d55d064\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Sec-WebSocket-Protocol: v4.channel.k8s.io, v3.channel.k8s.io, v2.channel.k8s.io, channel.k8s.io\r\n' +
        'Host: 128cdc15-fb51-471c-bca3-62a9e20a7f53.k8s.ondigitalocean.com\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7/exec?stdout=true&stderr=true&stdin=true&tty=true&command=ls&container=proftpd-pod',
      _ended: true,
      res: [IncomingMessage],
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '128cdc15-fb51-471c-bca3-62a9e20a7f53.k8s.ondigitalocean.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'Unexpected server response: 400',
  error: Error: Unexpected server response: 400
      at ClientRequest.<anonymous> (/home/brad/Documents/foundry-v2/website/main/node_modules/ws/lib/websocket.js:576:7)
      at ClientRequest.emit (events.js:315:20)
      at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
      at TLSSocket.socketOnData (_http_client.js:509:22)
      at TLSSocket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:284:9)
      at TLSSocket.Readable.push (_stream_readable.js:223:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

```

To ensure it works I run.
```
kubectl exec prosftpd-pod-584bd54ffc-24gq7 -it --v=8 ls
```
The out put of this is...
```
I1114 20:04:10.093260    6469 round_trippers.go:420] GET https://128cdc15-fb51-471c-bca3-62a9e20a7f53.k8s.ondigitalocean.com/api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7
I1114 20:04:10.093304    6469 round_trippers.go:427] Request Headers:
I1114 20:04:10.093321    6469 round_trippers.go:431]     Accept: application/json, */*
I1114 20:04:10.093336    6469 round_trippers.go:431]     User-Agent: kubectl/v1.19.3 (linux/amd64) kubernetes/1e11e4a
I1114 20:04:10.857065    6469 round_trippers.go:446] Response Status: 200 OK in 763 milliseconds
I1114 20:04:10.857169    6469 round_trippers.go:449] Response Headers:
I1114 20:04:10.857197    6469 round_trippers.go:452]     Audit-Id: 0f3d8225-2be0-459d-8b79-66547fefc0a6
I1114 20:04:10.857212    6469 round_trippers.go:452]     Cache-Control: no-cache, private
I1114 20:04:10.857235    6469 round_trippers.go:452]     Content-Type: application/json
I1114 20:04:10.857249    6469 round_trippers.go:452]     Date: Sun, 15 Nov 2020 04:04:10 GMT
I1114 20:04:10.857503    6469 request.go:1097] Response Body: {"kind":"Pod","apiVersion":"v1","metadata":{"name":"prosftpd-pod-584bd54ffc-24gq7","generateName":"prosftpd-pod-584bd54ffc-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7","uid":"3ea0a8ff-841a-4320-a169-7ea71ec92629","resourceVersion":"9870527","creationTimestamp":"2020-11-09T00:54:51Z","labels":{"app":"prosftpd-pod","pod-template-hash":"584bd54ffc"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"ReplicaSet","name":"prosftpd-pod-584bd54ffc","uid":"40117ab6-38e3-436e-9373-f02288ec36ee","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2020-11-09T00:54:51Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:app":{},"f:pod-template-hash":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"40117ab6-38e3-436e-9373-f02288ec36ee\"}":{".":{},"f:apiVersion":{},"f:blockOwnerDeletion":{},"f:controller":{},"f:kind":{},"f:name":{},"f:uid": [truncated 4860 chars]
I1114 20:04:10.872254    6469 round_trippers.go:420] POST https://128cdc15-fb51-471c-bca3-62a9e20a7f53.k8s.ondigitalocean.com/api/v1/namespaces/default/pods/prosftpd-pod-584bd54ffc-24gq7/exec?command=ls&container=prosftpd-pod&stdin=true&stdout=true&tty=true
```

**Comment by Daxcor69** [comment]
could this be a version issue, the cluster is 1.18.8 and the client version I have is 0.13.0, the readme shows a "+" for compatibility, could this be one of the items that is not supported?

**Comment by brendandburns** [comment]
No, this should work that protocol hasn't changed in a while. I will validate that this works in my local cluster.

**Comment by brendandburns** [comment]
Can you print out the body from that response, it should contain some details about why it is a bad request.

**Comment by Daxcor69** [comment]
I am sorry, I am still learning how to use the api and javascript. I can't figure out how to see the contents of the body.  I will keep working at it and post when I figure out how to do that.

**Comment by Daxcor69** [comment]
ok, I was able to get this method to work.  There is something in the os of the pod I am trying to access that is erroring out the exec command.  I started up a simple ubuntu shell and I was able to use the method to successfully exec "ls" on the pod. I would consider this issue closed, as I don't think it is an issue with this package.  If you think I have found something that is unique, I am happy to provide you more information.  I do have a question, I can send 'ls' as a command but  I cant send 'ls -la' as it errors out. How can I send a command with arguments?

**Comment by Daxcor69** [comment]
ok I think you should just delete this whole issue as I clearly don't know what I am talking about.  It now works. I am sorry to waste your time.

**Comment by brendandburns** [comment]
Given what you are saying, I think the problem may have been that the container was exiting. e.g. you were trying to connect to a Pod that wasn't running.

Regardless, I'm glad you got it working. Closing this issue.

**Comment by luyangsc** [comment]
How do you solve the problem?
I had the same problem。
i can use k8sApi.listNamespacedPod，but exec.exe(... return errotr 400

**Comment by bayerlse** [comment]
> You can't use CoreV1API for exec (sorry we should probably strip those methods from swagger before generating) please have a look at the exec example here:
> 
> https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/exec/exec-example.ts

Hey there, I cant use the exec you suggested, because I need a special auth which I set like this:

```ts
this.coreApiClient.setDefaultAuthentication({
                    applyToRequest: (opts) => {
                        opts.ca = Buffer.from(masterAuth.clusterCaCertificate!, 'base64');
                        opts.headers!.Authorization = 'Bearer ' + accessToken;
                    }
                });
```

But I cant set the defaultAuthentication when using Exec Class?

Any help here?

THanks, Sebi
