### ISSUE TITLE
Auth and exec from lambda

### ISSUE THREAD

**Issue by minotaurrr** [kubernetes-client/javascript#567]
I cannot figure this one out.. 

Trying to let lambda to login to a pod and execute a command.

```
const cluster = {
  name: process.env.CLUSTER_NAME,
  cluster: {
    'certificate-authority-data': process.env.CA_AUTHORITY,
    server: process.env.CLUSTER_ENDPOINT,
    skipTLSVerify: true,
  },
};

const user = {
  name: 'lambda',
  token: getBearerToken(process.env.CLUSTER_NAME),
};

  const kc = new k8s.KubeConfig();
  kc.loadFromClusterAndUser(cluster, user);

  const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
  k8sApi
    .listNamespacedPod(process.env.NAMESPACE)
    .then((res) => {
      const podName = res.body.items[0].metadata.name;
      console.log('connecting to pod:', podName); // i can see this printing in the log

      const containerExec = new k8s.Exec(kc);
      const command = `ls -a`.split(' ');
      containerExec
        .exec(process.env.NAMESPACE, podName, process.env.CONTAINER_NAME, command, process.stdout, process.stderr, process.stdin, true /* tty */, (status) => {
          console.log('<Exited with status:>');
          console.log(JSON.stringify(status, null, 2));
        })
        .then(() => {})
        .catch((err) => {
          console.log(err);
        });
    })
    .catch((err) => console.log(err));
```

I get this error

```
ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      error: [Function],
      message: [Function]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 3,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://xxxx.yl4.ap-southeast-2.eks.amazonaws.com/api/v1/namespaces/my-container/pods/my-pod-5d485bfffb-fnclt/exec?stdout=true&stderr=true&stdin=true&tty=true&command=hostname&container=trackside',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'GET /api/v1/namespaces/my-container/pods/my-pod-5d485bfffb-fnclt/exec?stdout=true&stderr=true&stdin=true&tty=true&command=hostname&container=<container_name> HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: E7XvQSw5SQm+iniRRGaqXA==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Authorization: Bearer k8s-aws-v1.aHR0cHM6Ly9zdH.....\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Sec-WebSocket-Protocol: v4.channel.k8s.io, v3.channel.k8s.io, v2.channel.k8s.io, channel.k8s.io\r\n' +
        'Host: xxxx.yl4.ap-southeast-2.eks.amazonaws.com\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/api/v1/namespaces/my-container/pods/my-pod-5d485bfffb-fnclt/exec?stdout=true&stderr=true&stdin=true&tty=true&command=hostname&container=trackside',
      _ended: true,
      res: [IncomingMessage],
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'xxxx.yl4.ap-southeast-2.eks.amazonaws.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'Unexpected server response: 400',
  error: Error: Unexpected server response: 400
      at ClientRequest.<anonymous> (/var/task/node_modules/ws/lib/websocket.js:604:7)
      at ClientRequest.emit (events.js:314:20)
      at HTTPParser.parserOnIncomingClient (_http_client.js:602:27)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
      at TLSSocket.socketOnData (_http_client.js:475:22)
      at TLSSocket.emit (events.js:314:20)
      at addChunk (_stream_readable.js:298:12)
      at readableAddChunk (_stream_readable.js:273:9)
      at TLSSocket.Readable.push (_stream_readable.js:214:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
}
```

Any idea why?

**Comment by brendandburns** [comment]
Your best bet is to print the response body, it's likely to have more details about why this is a bad request.

**Comment by minotaurrr** [comment]
@brendandburns thanks, the container name was wrong in this case.. closing

**Comment by gbvanrenswoude** [comment]
@minotaurrr can you share the details of your user object, and specifically the `getBearerToken()` ?
```js
const user = {
  name: 'lambda',
  token: getBearerToken(process.env.CLUSTER_NAME),
};
```
