### ISSUE TITLE
Trying to connect to EKS

### ISSUE THREAD

**Issue by wizzed** [kubernetes-client/javascript#577]
I was trying to connect to EKS, but the error occurs when this piece of code is run
```
let k8s = require("@kubernetes/client-node");
    const kc = new k8s.KubeConfig();

   kc.loadFromFile("./extra/kube.config");
    const k8sApi = kc.makeApiClient(k8s.AppsV1Api);
    k8sApi.listNamespacedDeployment("xxxxxx-sandbox").then(res => {
      console.log(res);
    });
```

The error is as follows:
```
(node:262) UnhandledPromiseRejectionWarning: Error: spawnSync aws ENOENT

    at Object.spawnSync (internal/child_process.js:1002:20)
    at Object.spawnSync (child_process.js:614:24)
    at ExecAuth.module.exports.sync [as execFn] (/app/node_modules/@kubernetes/client-node/node_modules/execa/index.js:334:30)
    at ExecAuth.getCredential (/app/node_modules/@kubernetes/client-node/dist/exec_auth.js:81:29)
    at ExecAuth.<anonymous> (/app/node_modules/@kubernetes/client-node/dist/exec_auth.js:24:37)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:111:16)
    at ExecAuth.applyAuthentication (/app/node_modules/@kubernetes/client-node/dist/exec_auth.js:23:24)
    at KubeConfig.<anonymous> (/app/node_modules/@kubernetes/client-node/dist/config.js:328:37)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:111:16)
    at KubeConfig.applyAuthorizationHeader (/app/node_modules/@kubernetes/client-node/dist/config.js:316:24)
    at KubeConfig.<anonymous> (/app/node_modules/@kubernetes/client-node/dist/config.js:338:24)
    at Generator.next (<anonymous>)
    at /app/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/app/node_modules/tslib/tslib.js:111:16)
    at KubeConfig.applyOptions (/app/node_modules/@kubernetes/client-node/dist/config.js:336:24)
```

I tried looking at #566, but it's a different problem I guess.

**Comment by brendandburns** [comment]
That is perhaps not a great error message, but I think that the problem is that the command to get the AWS token doesn't exist in your path.

Have a look at your Kubeconfig and look for the command in there and validate that it is on your PATH
