### ISSUE TITLE
Exec example for copying files to pod

### ISSUE THREAD

**Issue by cmosgh** [kubernetes-client/javascript#67]
Managed to download file from pod by creating a writestream and using it as stdout
```
const downloadCommand = ["tar", "czpf", "-", `${remotePath}`];
const localFile = fs.createWriteStream(localPath);
Exec.exec(nameSpace, podName, containerName, downloadCommand, localFile, null, null, true);
``` 

But I wouldn't know how to upload a file/folder to the container.

Anyone can help me out?

**Comment by brendandburns** [comment]
The `exec` command takes streams for `stdin`

If you path a stream that contains the tar file as the stdin stream and the command should be a command that untars from stdin.

Hope that helps.

**Comment by cmosgh** [comment]
@brendandburns  Any ideas what am I doing wrong?
```
const file = fs.createReadStream(tmpTarResultFile);//which I have and I can see it is a proper tgz
const uploadCommand = ["tar", "xzf", "-"];
Exec.exec(namespace, podName, containerName, uploadCommand, null, null, file, false);
```
And I am always getting 
```
buffer.js:186
    throw new TypeError('"value" argument must not be a number');
    ^

TypeError: "value" argument must not be a number
    at Function.Buffer.from (buffer.js:186:11)
    at ReadStream.stdin.on (/pathToProject/node_modules/@kubernetes/client-node/dist/web-socket-handler.js:42:33)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at ReadStream.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by cmosgh** [comment]
Done some digging and it seems that 
https://github.com/kubernetes-client/javascript/blob/master/node-client/src/web-socket-handler.ts#L46 should be 
```
const buff = Buffer.from(data, data.length + 1);
``` 
instead of 
```
const buff = Buffer.from(data.length + 1);
```

**Comment by cmosgh** [comment]
Created a PR https://github.com/kubernetes-client/javascript/pull/69 and followed the instructions for cla/linuxfoundation but it still says its not ok.
