### ISSUE TITLE
Error: HTTP request failed when calling k8s API

### ISSUE THREAD

**Issue by chainhead** [kubernetes-client/javascript#674]
**Describe the bug**
I am trying the Javascript client with the Kubernetes cluster available in Docker Desktop. I keep getting an error `HTTP request failed`. The `$HOME/.kube/config` has entry for `docker-desktop` only. This is the function.

```js
function namespaceExists(ns) {
  k8sApi.readNamespace({
    metadata: {
      name: ns
    }
  })
    .then((resp) => {
      return { check: true, msg: "" }
    })
    .catch((err) => {
      console.log(`Namespace was not found ${ns}. Error: ${err.message}`)
      return { check: false, msg: `Namespace was not found ${ns}.` }
    })
}
```

** Client Version **
e.g. `0.12.0`

** Server Version **
e.g. `1.19.1`

**To Reproduce**
1.  Run the following `js` snippet against a Kubernetes cluster - `docker-desktop` or `kind`.

```js
function namespaceExists(ns) {
  k8sApi.readNamespace({
    metadata: {
      name: ns
    }
  })
    .then((resp) => {
      console.log(`Namespace was found ${ns}.`)
    })
    .catch((err) => {
      console.log(`Namespace was not found ${ns}. Error: ${err.message}`)
    })
}
```

**Expected behavior**
A response as either `Namespace was found ${ns}.` or `Namespace was not found ${ns}.`

** Example Code**
See above.

**Environment (please complete the following information):**
 - OS: Mac 11.4
 - NodeJS Version: v12.18.2
 - Cloud runtime: Not applicable.

**Comment by brendandburns** [comment]
I can't reproduce this and we need more details. Can you try placing a `try { ... } catch(...)` around that code block and see if that catches an exception? I suspect that there is an exception that is somehow escaping the promise without triggering your `catch` block.

**Comment by chainhead** [comment]
Based on the documentation of `readNamespace`, I think, my code snippet above is wrong. The `readNamespace` function uses `{name: namespaceString}` as input as shown below. The result is still the same.

```js
const k8s = require('@kubernetes/client-node');
const kc = new k8s.KubeConfig();

kc.loadFromDefault();
const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

function namespaceExists(ns) {
  k8sApi.readNamespace({
    name: ns
  }).then(() => {
    console.log(`Namespace found.`)
    return {check:true}    
  }).catch((e) => {
    console.log(`Namespace not found. ${e.message}`)
    return {check:false}    
  })
}

namespaceExists("demo")
```

I used the `try..catch` option as below (hope I got it right!).

```js
const k8s = require('@kubernetes/client-node');
const kc = new k8s.KubeConfig();

kc.loadFromDefault();
const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

function namespaceExists(ns) {
  try {
    k8sApi.readNamespace({
      name: ns
    })
    console.log(`ns ${ns} found.`)
  } catch (e) {
    console.log(`ns ${ns} not found.`)
    console.log(`${e.message}`)
  }
}

namespaceExists("demo")
```

This is the result.

```bash
ns demo found.
(node:80223) UnhandledPromiseRejectionWarning: HttpError: HTTP request failed
    at Request._callback (/Users/user01/temp/js/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:14211:40)
    at Request.self.callback (/Users/user01/temp/js/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/user01/temp/js/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/Users/user01/temp/js/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:80223) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:80223) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by brendandburns** [comment]
Thanks for the clarity.

I believe that this is throwing because `e.message` is not defined.

switch `console.log(`${e.message}`)` to `console.log(e);`

and I think that you should get more details about what is going wrong.

**Comment by chainhead** [comment]
So, `e.statusCode` is `404` even though the namespace exists.

**Comment by brendandburns** [comment]
@chainhead something is wrong with either your kube-config, there is a typo somewhere in your code or you have some sort of misconfigured HTTP proxy in the way.
