### ISSUE TITLE
Always Got Error: Forbidden from Informer

### ISSUE THREAD

**Issue by johnico** [kubernetes-client/javascript#679]
**Describe the bug**
trying to work with informer and I got Error: Forbidden evrery run 
I still get the updates from the informer but with the Error: Forbidden
** Client Version **
0.14.3

** Example Code**
```
const listFn = () => k8sApi.listNamespacedPod('testi',null,null,null,null,'label=x');
const informer = makeInformer(kc, '/api/v1/pods', listFn);

informer.on('add', (pod) => { console.log(`Added: ${pod.metadata!.name}`); });
informer.on('update', (pod) => { console.log(`Updated: ${pod.metadata!.name}`);  });
informer.on('delete', (pod) => { console.log(`Deleted: ${pod.metadata!.name}`); });
informer.on('error', (err) => {
  console.log(err)
  // Restart informer after 5sec
  setTimeout(() => informer.start(), 5000)
})

informer.start(
```

Full error:

```
Error: Forbidden
    at Request.<anonymous> (/node_modules/@kubernetes/client-node/dist/watch.js:24:35)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.onRequestResponse (/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
Error: Forbidden
    at Request.<anonymous> (/....node_modules/@kubernetes/client-node/dist/watch.js:24:35)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.onRequestResponse (...../node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
```

**Comment by brendandburns** [comment]
Your authentication isn't working right. Where are you making this call from? What is the authentication that you are using?

**Comment by johnico** [comment]
hi thanks, it was an authentication issue
