### ISSUE TITLE
Outdated dependency to `shelljs` is printing unwanted warnings

### ISSUE THREAD

**Issue by ArchangelX360** [kubernetes-client/javascript#684]
**Describe the bug**
Dependency `shelljs` in version `0.8.3` is printing warnings with specific versions of NodeJS, see https://github.com/shelljs/shelljs/issues/992.

As `@kubernetes/client-node` depends on it, we are seeing those warnings at runtime:
```
(node:29099) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
    at emitCircularRequireWarning (node:internal/modules/cjs/loader:703:11)
    at Object.get (node:internal/modules/cjs/loader:717:5)
    at Object._register [as register] ([REDACTED]/node_modules/@kubernetes/client-node/node_modules/shelljs/src/common.js:453:12)
    at Object.<anonymous> ([REDACTED]/node_modules/@kubernetes/client-node/node_modules/shelljs/src/cat.js:4:8)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
// ...
```

Upgrading to `shelljs` `0.8.4` should be sufficient to resolve the issue.

** Client Version **
`0.12.3`

** Server Version **
N/A

**Expected behavior**
No warnings

**Environment (please complete the following information):**
 - OS: MacOS BigSur
 - NodeJS Version 16.3.0

**Additional context**

**Comment by brendandburns** [comment]
Closing this since #685 merged and `0.15.0` has been pushed with the fix.
