### ISSUE TITLE
422 When trying to deleteNamespacedJob with propogationPolicy

### ISSUE THREAD

**Issue by danthegoodman1** [kubernetes-client/javascript#723]
k8s 1.21 and client 0.15.0

When trying to deleted a completed job with `await client.deleteNamespacedJob(jobName, 'default', undefined, undefined, undefined, undefined, 'Background')` (using `undefined`'s to get to the `propogationPolicy`), I receive the following error.

It seems like instead of using the `DELETE` endpoint, it is attempting to `PATCH` first.

```json
{
  "level": "error",
  "time": 1632680889443,
  "pid": 18,
  "hostname": "api-6568df8b88-628nz",
  "response": {
    "statusCode": 422,
    "body": {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {},
      "status": "Failure",
      "message": "Job.batch \"build-app-qfspajcacytb\" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"controller-uid\":\"033642da-1a45-4380-b3c8-1d6e39e72896\", \"job-name\":\"build-app-qfspajcacytb\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:\"\", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:\"docker-secret\", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(0xc010559e80), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil), Ephemeral:(*core.EphemeralVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:\"build\", Image:\"gcr.io/kaniko-project/executor:latest\", Command:[]string(nil), Args:[]string{\"--dockerfile=Dockerfile\", \"--context=https://test-nyc3.nyc3.digitaloceanspaces.com/app-qfspajcacytb-1632680889378.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=77OAXO5BJDRQDYH7W3LM%2F20210926%2Fnyc-3%2Fs3%2Faws4_request&X-Amz-Date=20210926T182809Z&X-Amz-Expires=3600&X-Amz-Signature=742877f6e423dffc4dd3401e926378be4171699b1fded14833e9b907e9e8f464&X-Amz-SignedHeaders=host&x-id=GetObject\", \"--destination=registry.digitalocean.com/cs-reg/app-qfspajcacytb:1\"}, WorkingDir:\"\", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:\"docker-secret\", ReadOnly:false, MountPath:\"/kaniko/.docker\", SubPath:\"\", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:\"\"}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:\"/dev/termination-log\", TerminationMessagePolicy:\"File\", ImagePullPolicy:\"Always\", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:\"Never\", TerminationGracePeriodSeconds:(*int64)(0xc01fb18120), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:\"ClusterFirst\", NodeSelector:map[string]string(nil), ServiceAccountName:\"\", AutomountServiceAccountToken:(*bool)(nil), NodeName:\"\", SecurityContext:(*core.PodSecurityContext)(0xc0086b1100), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:\"\", Subdomain:\"\", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:\"default-scheduler\", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:\"\", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable",
      "reason": "Invalid",
      "details": {
        "name": "build-app-qfspajcacytb",
        "group": "batch",
        "kind": "Job",
        "causes": [
          {
            "reason": "FieldValueInvalid",
            "message": "Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"controller-uid\":\"033642da-1a45-4380-b3c8-1d6e39e72896\", \"job-name\":\"build-app-qfspajcacytb\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:\"\", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:\"docker-secret\", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(0xc010559e80), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil), Ephemeral:(*core.EphemeralVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:\"build\", Image:\"gcr.io/kaniko-project/executor:latest\", Command:[]string(nil), Args:[]string{\"--dockerfile=Dockerfile\", \"--context=https://test-nyc3.nyc3.digitaloceanspaces.com/app-qfspajcacytb-1632680889378.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=77OAXO5BJDRQDYH7W3LM%2F20210926%2Fnyc-3%2Fs3%2Faws4_request&X-Amz-Date=20210926T182809Z&X-Amz-Expires=3600&X-Amz-Signature=742877f6e423dffc4dd3401e926378be4171699b1fded14833e9b907e9e8f464&X-Amz-SignedHeaders=host&x-id=GetObject\", \"--destination=registry.digitalocean.com/cs-reg/app-qfspajcacytb:1\"}, WorkingDir:\"\", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:\"docker-secret\", ReadOnly:false, MountPath:\"/kaniko/.docker\", SubPath:\"\", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:\"\"}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:\"/dev/termination-log\", TerminationMessagePolicy:\"File\", ImagePullPolicy:\"Always\", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:\"Never\", TerminationGracePeriodSeconds:(*int64)(0xc01fb18120), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:\"ClusterFirst\", NodeSelector:map[string]string(nil), ServiceAccountName:\"\", AutomountServiceAccountToken:(*bool)(nil), NodeName:\"\", SecurityContext:(*core.PodSecurityContext)(0xc0086b1100), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:\"\", Subdomain:\"\", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:\"default-scheduler\", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:\"\", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable",
            "field": "spec.template"
          }
        ]
      },
      "code": 422
    },
    "headers": {
      "audit-id": "443bf3cc-014c-4f5b-b501-804362814939",
      "cache-control": "no-cache, private",
      "content-type": "application/json",
      "x-kubernetes-pf-flowschema-uid": "a3198aae-1f5e-41d3-8a0e-258a00788562",
      "x-kubernetes-pf-prioritylevel-uid": "dfc5161a-6b41-415e-837c-c4a43e61a2c3",
      "date": "Sun, 26 Sep 2021 18:28:09 GMT",
      "connection": "close",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "10.245.0.1:443",
        "port": "443",
        "hostname": "10.245.0.1",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/apis/batch/v1/namespaces/default/jobs/build-app-qfspajcacytb",
        "path": "/apis/batch/v1/namespaces/default/jobs/build-app-qfspajcacytb",
        "href": "https://10.245.0.1:443/apis/batch/v1/namespaces/default/jobs/build-app-qfspajcacytb"
      },
      "method": "PATCH",
      "headers": {
        "accept": "application/json",
        "content-type": "application/merge-patch+json",
        "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImxyZUVkV3JSRXJEYVNBYmlLQUNJNzdvY0RRbnNkNi1fZ1Nsdmpsc1JGd1EifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjY0MjE2NzkzLCJpYXQiOjE2MzI2ODA3OTMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJhcGkiLCJwb2QiOnsibmFtZSI6ImFwaS02NTY4ZGY4Yjg4LTYyOG56IiwidWlkIjoiNmJjYzVhYmYtODE4Ny00MjdkLThkNzEtOGViZjRlYzMxNWZhIn0sInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhcGkiLCJ1aWQiOiJiZTdmZWMyYS02YjUxLTQzOTItYThjZC01ODIyMWJiMmZlZGEifSwid2FybmFmdGVyIjoxNjMyNjg0NDAwfSwibmJmIjoxNjMyNjgwNzkzLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6YXBpOmFwaSJ9.MRLpqG0T4dHs9rDT5fqApOg0_0qaIC3spzAbxe0wsMW3eTduecTmS3tM2YWuRxTGrM2bYy67Yfx9lIH6ePJH8SZHuc08BSN488Wlcrj1h85ujvVsN1Lrw23KokQ-AT4_Bb4TYUh7urD5qzymXisY7noqEkDPy5NJ0Url5JpvihimAtn1BaxqLSZ6BzsGpSI7fvW6ISLbVb_QuqVNzTdun15fAKHG5PkvT8guJQSHO02VSidxxJBHeadgmSjnH1j6WnLExsnHaWGCmf3Akfcx_Yd_f41rZ0j2e-_C8kaeE4BvdvH7sPc-KsOswr08nbSJUvvujd1SZ2e3oo058fFkUw",
        "content-length": 923
      }
    }
  },
  "body": {
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Job.batch \"build-app-qfspajcacytb\" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"controller-uid\":\"033642da-1a45-4380-b3c8-1d6e39e72896\", \"job-name\":\"build-app-qfspajcacytb\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:\"\", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:\"docker-secret\", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(0xc010559e80), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil), Ephemeral:(*core.EphemeralVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:\"build\", Image:\"gcr.io/kaniko-project/executor:latest\", Command:[]string(nil), Args:[]string{\"--dockerfile=Dockerfile\", \"--context=https://test-nyc3.nyc3.digitaloceanspaces.com/app-qfspajcacytb-1632680889378.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=77OAXO5BJDRQDYH7W3LM%2F20210926%2Fnyc-3%2Fs3%2Faws4_request&X-Amz-Date=20210926T182809Z&X-Amz-Expires=3600&X-Amz-Signature=742877f6e423dffc4dd3401e926378be4171699b1fded14833e9b907e9e8f464&X-Amz-SignedHeaders=host&x-id=GetObject\", \"--destination=registry.digitalocean.com/cs-reg/app-qfspajcacytb:1\"}, WorkingDir:\"\", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:\"docker-secret\", ReadOnly:false, MountPath:\"/kaniko/.docker\", SubPath:\"\", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:\"\"}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:\"/dev/termination-log\", TerminationMessagePolicy:\"File\", ImagePullPolicy:\"Always\", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:\"Never\", TerminationGracePeriodSeconds:(*int64)(0xc01fb18120), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:\"ClusterFirst\", NodeSelector:map[string]string(nil), ServiceAccountName:\"\", AutomountServiceAccountToken:(*bool)(nil), NodeName:\"\", SecurityContext:(*core.PodSecurityContext)(0xc0086b1100), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:\"\", Subdomain:\"\", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:\"default-scheduler\", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:\"\", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable",
    "reason": "Invalid",
    "details": {
      "name": "build-app-qfspajcacytb",
      "group": "batch",
      "kind": "Job",
      "causes": [
        {
          "reason": "FieldValueInvalid",
          "message": "Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"controller-uid\":\"033642da-1a45-4380-b3c8-1d6e39e72896\", \"job-name\":\"build-app-qfspajcacytb\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:\"\", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:\"docker-secret\", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(0xc010559e80), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(nil), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil), CSI:(*core.CSIVolumeSource)(nil), Ephemeral:(*core.EphemeralVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:\"build\", Image:\"gcr.io/kaniko-project/executor:latest\", Command:[]string(nil), Args:[]string{\"--dockerfile=Dockerfile\", \"--context=https://test-nyc3.nyc3.digitaloceanspaces.com/app-qfspajcacytb-1632680889378.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=77OAXO5BJDRQDYH7W3LM%2F20210926%2Fnyc-3%2Fs3%2Faws4_request&X-Amz-Date=20210926T182809Z&X-Amz-Expires=3600&X-Amz-Signature=742877f6e423dffc4dd3401e926378be4171699b1fded14833e9b907e9e8f464&X-Amz-SignedHeaders=host&x-id=GetObject\", \"--destination=registry.digitalocean.com/cs-reg/app-qfspajcacytb:1\"}, WorkingDir:\"\", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:\"docker-secret\", ReadOnly:false, MountPath:\"/kaniko/.docker\", SubPath:\"\", MountPropagation:(*core.MountPropagationMode)(nil), SubPathExpr:\"\"}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), StartupProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:\"/dev/termination-log\", TerminationMessagePolicy:\"File\", ImagePullPolicy:\"Always\", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:false}}, EphemeralContainers:[]core.EphemeralContainer(nil), RestartPolicy:\"Never\", TerminationGracePeriodSeconds:(*int64)(0xc01fb18120), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:\"ClusterFirst\", NodeSelector:map[string]string(nil), ServiceAccountName:\"\", AutomountServiceAccountToken:(*bool)(nil), NodeName:\"\", SecurityContext:(*core.PodSecurityContext)(0xc0086b1100), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:\"\", Subdomain:\"\", SetHostnameAsFQDN:(*bool)(nil), Affinity:(*core.Affinity)(nil), SchedulerName:\"default-scheduler\", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:\"\", Priority:(*int32)(nil), PreemptionPolicy:(*core.PreemptionPolicy)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), RuntimeClassName:(*string)(nil), Overhead:core.ResourceList(nil), EnableServiceLinks:(*bool)(nil), TopologySpreadConstraints:[]core.TopologySpreadConstraint(nil)}}: field is immutable",
          "field": "spec.template"
        }
      ]
    },
    "code": 422
  },
  "statusCode": 422,
  "name": "HttpError",
  "stack": "HttpError: HTTP request failed\n    at Request._callback (/app/node_modules/@kubernetes/client-node/dist/object.js:416:32)\n    at Request.self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:400:28)\n    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:400:28)\n    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:519:28)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1317:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)",
  "type": "Error",
  "message": "HTTP request failed"
}
```

**Comment by brendandburns** [comment]
The code for that particular function is here:

https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/batchV1Api.ts#L714

You can see that it is setting the method to `DELETE` so I'm not sure what is happening here, I suspect there is a code error somewhere on your side, or that error is actually unrelated to the call.

**Comment by danthegoodman1** [comment]
@brendanburns This is what I thought to be the case initially too, however looking at my code (where I do mix some DELETE and PATCH operations), I never perform a patch on a Job object, only a delete. Here is the code used:

```
export async function DeleteJob(jobName: string) {
  try {
    const kubeConfig = createK8sClient('a', 'a', 'a')
    const client = makeBatchAPIClient(kubeConfig)
    const r = await client.deleteNamespacedJob(jobName, 'default')
    logger.info({
      jobName,
      response: r
    }, 'deleted kubernetes job')
  } catch (error: any) {
    logger.error('Error deleting k8s job!')
    logger.error(error)
    throw error
  }
}
```

I have also only observed this issue when using the `client.deleteNamespaceJob()` with the propogationPolicy as show in this line:
```
await client.deleteNamespacedJob(jobName, 'default', undefined, undefined, undefined, undefined, 'Background')
```

If I omit those extra arguments and use just the 2 shown in the first example, this error does not throw.

**Comment by brendandburns** [comment]
Have you tried using a 'V1DeleteOptions' object instead of the propogationPolicy query arg?

https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#use-background-cascading-deletion

**Comment by danthegoodman1** [comment]
I have not. I will try and report back when I can!
